#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - 103-windows-build

  # blacklist
  except:
    - master
    - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
# - git submodule update --init --recursive

# clone directory
clone_folder: c:\projects\nupic-core

environment:
  matrix:
#    - COMPILER_FAMILY: GNU
    - COMPILER_FAMILY: MSVC

#  fast_finish: true
#  allow_failures:
#    - platform: x86
#      configuration: Debug
#    - platform: x64
#      configuration: Debug


# scripts that run after cloning repository
install:
  echo "Compiler family: %COMPILER_FAMILY%"
  echo %PATH%
  
  mkdir C:\projects\nupic-core\build\
  mkdir C:\projects\nupic-core\build\scripts
  cd C:\projects\nupic-core\build\scripts

  IF "%COMPILER_FAMILY%" == "GNU" cmake C:\projects\nupic-core\src -G "MSYS Makefiles"
  IF "%COMPILER_FAMILY%" == "MSVC" cmake C:\projects\nupic-core\src -G "Visual Studio 12"

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x86
#  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
#  - Debug
  - Release

# scripts to run before build
before_build:

build:
#  project: NuPIC.core.sln         # path to Visual Studio solution or project
#  publish_wap: true               # package Web Application Projects (WAP) for Web Deploy
#  publish_wap_xcopy: true         # package Web Application Projects (WAP) for XCopy deployment
#  publish_azure: true             # package Azure Cloud Service projects and push to artifacts
  publish_nuget: true             # package projects with .nuspec files and push to artifacts

  # MSBuild verbosity level
  #verbosity: normal               #quiet|minimal|normal|detailed

# to run your custom scripts instead of automatic MSBuild
build_script:
  cd C:\projects\nupic-core\build\scripts

  IF "%COMPILER_FAMILY%" == "GNU" make
  IF "%COMPILER_FAMILY%" == "MSVC" msbuild nupic_core.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

# scripts to run after build
after_build:
  cd C:\projects\nupic-core\build\release
  DIR
  cd C:\projects\nupic-core\build\temp
  DIR
  cd C:\projects\nupic-core
  PWD

#after_test:
#  - ps: .\nuget\pack.ps1
    
#build: off
#test: off
deploy: off

